[build]

# Pi 1
[target.arm-unknown-linux-gnueabihf]
linker = "/mnt/c/Users/wellerm/dev/cross-pi-gcc/bin/arm-linux-gnueabihf-gcc"

# Pi 2/3/4
[target.armv7-unknown-linux-gnueabihf]
linker = "arm-linux-gnueabihf-gcc"